config: test

verbose: true

io:
  google:
    project: "king-ds-recruit-candidate-91"
    dataset: "abtest"
    table: 
      - "activity"
      - "assignment"
  output:
    model_output:
      "test_king/output"

model:
  model: log_lasso
  train_prop: 0.8
        
